### ISSUE TITLE
An empty list of rules and an incorrect definition of the current host

### ISSUE THREAD

**Issue by BodyulCG** [Lor-Saba/Code-Injector#11]
An empty list of rules and an incorrect definition of the current host.
Firefox 72.0.2
Code Injector 0.3.0

<img src="https://i.imgur.com/w0mur3Y.png" width="50%">
<img src="https://i.imgur.com/rgvsmQq.png">

**Comment by petehanson** [comment]
I'm seeing this as well, after the last update on 1/22. My rules disappeared and it doesn't seem to match any that add into the list. If I reload the page, the rules clear out again.

**Comment by BodyulCG** [comment]
> 
> 
> I'm seeing this as well, after the last update on 1/22. My rules disappeared and it doesn't seem to match any that add into the list. If I reload the page, the rules clear out again.

Now it works fine. In version 0.3.2, this is fixed.
